import { SubjectConfig } from '../subjectRegistry';

export const pythonConfig: SubjectConfig = {
  name: 'Python',
  color: {
    primary: '#3776AB',
    secondary: '#FFD43B',
    gradient: 'from-blue-500 to-yellow-400',
  },
  chapters: [
    {
      id: 'introduction',
      title: 'Introduction to Python',
      subtopics: [
        'What is Python?',
        'Why Python?',
        'Installing Python',
        'Python IDEs and Editors',
        'Your First Python Program',
        'Python Syntax Basics',
      ],
    },
    {
      id: 'basics',
      title: 'Python Basics',
      subtopics: [
        'Variables and Data Types',
        'Numbers and Math Operations',
        'Strings and String Methods',
        'Type Conversion',
        'Input and Output',
        'Comments and Documentation',
      ],
    },
    {
      id: 'control-flow',
      title: 'Control Flow',
      subtopics: [
        'If-Elif-Else Statements',
        'Comparison Operators',
        'Logical Operators',
        'For Loops',
        'While Loops',
        'Break, Continue, and Pass',
        'List Comprehensions',
      ],
    },
    {
      id: 'data-structures',
      title: 'Data Structures',
      subtopics: [
        'Lists',
        'Tuples',
        'Sets',
        'Dictionaries',
        'List Methods',
        'Dictionary Methods',
        'Nested Data Structures',
      ],
    },
    {
      id: 'functions',
      title: 'Functions',
      subtopics: [
        'Defining Functions',
        'Function Parameters',
        'Return Values',
        'Default Arguments',
        'Keyword Arguments',
        'Lambda Functions',
        'Scope and Lifetime',
      ],
    },
    {
      id: 'modules',
      title: 'Modules and Packages',
      subtopics: [
        'Importing Modules',
        'Creating Modules',
        'Standard Library',
        'Packages',
        'pip and Package Management',
        'Virtual Environments',
      ],
    },
    {
      id: 'oop',
      title: 'Object-Oriented Programming',
      subtopics: [
        'Classes and Objects',
        'Constructors and Methods',
        'Inheritance',
        'Encapsulation',
        'Polymorphism',
        'Magic Methods',
        'Class vs Instance Variables',
      ],
    },
    {
      id: 'file-handling',
      title: 'File Handling',
      subtopics: [
        'Reading Files',
        'Writing Files',
        'File Modes',
        'Context Managers',
        'Working with CSV',
        'Working with JSON',
      ],
    },
    {
      id: 'error-handling',
      title: 'Error and Exception Handling',
      subtopics: [
        'Try-Except Blocks',
        'Multiple Exceptions',
        'Finally Clause',
        'Raising Exceptions',
        'Custom Exceptions',
        'Debugging Techniques',
      ],
    },
    {
      id: 'advanced',
      title: 'Advanced Topics',
      subtopics: [
        'Decorators',
        'Generators',
        'Iterators',
        'Regular Expressions',
        'Working with Dates and Times',
        'Multithreading',
        'Web Scraping Basics',
      ],
    },
  ],
};
