import { SubjectConfig } from '../subjectRegistry';

export const algorithmsConfig: SubjectConfig = {
  name: 'Algorithms',
  color: {
    primary: '#10B981',
    secondary: '#059669',
    gradient: 'from-green-500 to-green-700',
  },
  chapters: [
    {
      id: 'introduction',
      title: 'Introduction to Algorithms',
      subtopics: [
        'What is an Algorithm?',
        'Algorithm Analysis',
        'Time Complexity',
        'Space Complexity',
        'Asymptotic Notation',
        'Best, Average, and Worst Case',
      ],
    },
    {
      id: 'searching',
      title: 'Searching Algorithms',
      subtopics: [
        'Linear Search',
        'Binary Search',
        'Jump Search',
        'Interpolation Search',
        'Exponential Search',
      ],
    },
    {
      id: 'sorting',
      title: 'Sorting Algorithms',
      subtopics: [
        'Bubble Sort',
        'Selection Sort',
        'Insertion Sort',
        'Merge Sort',
        'Quick Sort',
        'Heap Sort',
        'Counting Sort',
        'Radix Sort',
      ],
    },
    {
      id: 'divide-conquer',
      title: 'Divide and Conquer',
      subtopics: [
        'Divide and Conquer Strategy',
        'Merge Sort Analysis',
        'Quick Sort Analysis',
        'Binary Search Analysis',
        'Strassen\'s Matrix Multiplication',
        'Closest Pair of Points',
      ],
    },
    {
      id: 'greedy',
      title: 'Greedy Algorithms',
      subtopics: [
        'Greedy Strategy',
        'Activity Selection',
        'Fractional Knapsack',
        'Huffman Coding',
        'Job Sequencing',
        'Minimum Spanning Tree',
      ],
    },
    {
      id: 'dynamic-programming',
      title: 'Dynamic Programming',
      subtopics: [
        'DP Fundamentals',
        'Memoization vs Tabulation',
        'Fibonacci Numbers',
        '0/1 Knapsack Problem',
        'Longest Common Subsequence',
        'Matrix Chain Multiplication',
        'Edit Distance',
      ],
    },
    {
      id: 'backtracking',
      title: 'Backtracking',
      subtopics: [
        'Backtracking Concept',
        'N-Queens Problem',
        'Sudoku Solver',
        'Subset Sum',
        'Hamiltonian Path',
        'Graph Coloring',
      ],
    },
    {
      id: 'graph-algorithms',
      title: 'Graph Algorithms',
      subtopics: [
        'Breadth-First Search (BFS)',
        'Depth-First Search (DFS)',
        'Dijkstra\'s Algorithm',
        'Bellman-Ford Algorithm',
        'Floyd-Warshall Algorithm',
        'Kruskal\'s Algorithm',
        'Prim\'s Algorithm',
      ],
    },
    {
      id: 'string-algorithms',
      title: 'String Algorithms',
      subtopics: [
        'Pattern Matching',
        'Naive String Matching',
        'KMP Algorithm',
        'Rabin-Karp Algorithm',
        'Boyer-Moore Algorithm',
        'Longest Palindromic Substring',
      ],
    },
    {
      id: 'advanced',
      title: 'Advanced Algorithms',
      subtopics: [
        'Branch and Bound',
        'A* Search Algorithm',
        'Network Flow',
        'Maximum Bipartite Matching',
        'Approximation Algorithms',
        'Randomized Algorithms',
      ],
    },
  ],
};
