import React, { useEffect } from 'react';
import { ExerciseQuestion } from '../../../components/ExerciseQuestion';

interface Chapter4Props {
  selectedSubtopic?: string;
  onNavigateChapter?: (chapterId: string) => void;
  currentChapterId?: string;
}

export const Chapter4: React.FC<Chapter4Props> = ({ selectedSubtopic, onNavigateChapter }) => {
  useEffect(() => {
    if (selectedSubtopic) {
      const match = selectedSubtopic.match(/(\d+\.\d+)/);
      const subtopicId = match ? match[1] : selectedSubtopic.split('.').slice(0, 2).join('.').trim();
      const element = document.getElementById(`subtopic-${subtopicId}`) || document.getElementById(`subtopic-${selectedSubtopic}`);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }
  }, [selectedSubtopic]);

  return (
    <div className="w-full">
      {/* Hero Section */}
      <div className="relative mb-6 md:mb-12 px-0 md:px-8 py-4 md:py-8">
        <span className="inline-block px-3 md:px-4 py-1 md:py-1.5 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 text-[10px] md:text-xs font-bold tracking-widest uppercase mb-2 md:mb-4 rounded-full">
          Mathematics Chapter 4 • Comprehensive Master Guide
        </span>
        <h1 className="text-xl md:text-5xl font-black text-slate-900 dark:text-white leading-tight mb-3 md:mb-6 tracking-tight">
          TRIGONOMETRIC FUNCTIONS & ANALYTICAL IDENTITIES
        </h1>
        <div className="h-1 md:h-1.5 w-16 md:w-24 bg-gradient-to-r from-indigo-600 to-cyan-600 rounded-full" />
        <p className="mt-3 md:mt-6 text-xs md:text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
          Trigonometry forms the mathematical bridge between linear geometry and periodic motion analysis. This in-depth master guide covers radian angle conversions, circular motion kinematics, unit circle mapping, quadrant sign rules, 5-key-point sinusoidal wave graphing, inverse composition right-triangle methods, Pythagorean & double-angle identities, and trigonometric equation solving strategies.
        </p>
      </div>

      <div className="space-y-8 md:space-y-16 pb-10 md:pb-20 px-0 md:px-8">
        
        {/* SUBTOPIC 4.1: Angles and Their Measures */}
        <section id="subtopic-4.1" className="scroll-mt-8">
          <h2 className="text-base md:text-3xl font-bold text-slate-900 dark:text-white mb-3 md:mb-6 border-l-4 border-indigo-600 pl-2 md:pl-4 flex items-center gap-2">
            <span>📐</span> 4.1. Angles, Radian Measure & Circular Motion Kinematics
          </h2>

          <div className="space-y-4 md:space-y-6">
            <p className="text-xs md:text-lg text-slate-700 dark:text-slate-300 leading-relaxed">
              An angle is generated by rotating a ray about its endpoint (vertex). In standard position on the Cartesian plane, the vertex is at origin <em>(0,0)</em> and the <strong>initial side</strong> lies along the positive x-axis. Counterclockwise rotation yields positive angles; clockwise rotation yields negative angles.
            </p>

            {/* Radian vs Degree Conversion Box */}
            <div className="p-5 bg-indigo-50 dark:bg-indigo-900/20 rounded-2xl border border-indigo-200 dark:border-indigo-800 space-y-3">
              <h3 className="font-bold text-indigo-900 dark:text-indigo-300 text-sm md:text-base flex items-center gap-2">
                <span>🔄</span> Degree ↔ Radian Conversion Rules (180° = π rad)
              </h3>
              <div className="grid md:grid-cols-2 gap-4 font-mono text-xs md:text-sm">
                <div className="p-3 bg-white dark:bg-slate-900 rounded-xl border text-center">
                  <span className="font-sans font-bold block text-slate-700 dark:text-slate-300 text-xs mb-1">Degrees to Radians</span>
                  <div className="text-indigo-700 dark:text-indigo-300 font-bold">θ_rad = θ_deg × (π / 180°)</div>
                  <p className="text-[11px] font-sans text-slate-500 mt-1">Ex: 270° × (π/180°) = 3π/2 rad</p>
                </div>
                <div className="p-3 bg-white dark:bg-slate-900 rounded-xl border text-center">
                  <span className="font-sans font-bold block text-slate-700 dark:text-slate-300 text-xs mb-1">Radians to Degrees</span>
                  <div className="text-indigo-700 dark:text-indigo-300 font-bold">θ_deg = θ_rad × (180° / π)</div>
                  <p className="text-[11px] font-sans text-slate-500 mt-1">Ex: (5π/6) × (180°/π) = 150°</p>
                </div>
              </div>
            </div>

            {/* Coterminal Angles Card */}
            <div className="p-5 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 space-y-2">
              <h4 className="font-bold text-slate-900 dark:text-white text-sm md:text-base flex items-center gap-2">
                <span>🔁</span> Coterminal Angles Algorithm
              </h4>
              <p className="text-xs md:text-sm text-slate-600 dark:text-slate-300">
                Two angles in standard position are <strong>coterminal</strong> if they share the exact same terminal side. Any given angle θ has infinitely many coterminal angles given by:
              </p>
              <div className="p-3 bg-slate-50 dark:bg-slate-800 rounded-xl font-mono text-xs md:text-sm text-center font-bold text-indigo-700 dark:text-indigo-300">
                θ_coterminal = θ + 360° · k   (Degrees)   OR   θ_coterminal = θ + 2π · k   (Radians, k ∈ ℤ)
              </div>
            </div>

            {/* Circular Kinematics Grid */}
            <div className="grid md:grid-cols-3 gap-4 text-xs md:text-sm font-mono">
              <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border space-y-1">
                <span className="font-sans font-bold text-slate-900 dark:text-white text-sm block">📏 Arc Length (s)</span>
                <div className="p-2 bg-indigo-50 dark:bg-indigo-900/40 rounded font-bold text-indigo-800 dark:text-indigo-300 text-center">
                  s = r · θ
                </div>
                <p className="font-sans text-slate-600 dark:text-slate-400 text-xs">
                  Subtended arc length on circle of radius <em>r</em> with angle <em>θ</em> in radians.
                </p>
              </div>

              <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border space-y-1">
                <span className="font-sans font-bold text-slate-900 dark:text-white text-sm block">🍕 Sector Area (A)</span>
                <div className="p-2 bg-cyan-50 dark:bg-cyan-900/40 rounded font-bold text-cyan-800 dark:text-cyan-300 text-center">
                  A = (1/2) · r² · θ
                </div>
                <p className="font-sans text-slate-600 dark:text-slate-400 text-xs">
                  Area of pie-shaped circular sector enclosed by radius <em>r</em> and central angle <em>θ</em> in radians.
                </p>
              </div>

              <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border space-y-1">
                <span className="font-sans font-bold text-slate-900 dark:text-white text-sm block">⚡ Linear & Angular Speed</span>
                <div className="p-2 bg-emerald-50 dark:bg-emerald-900/40 rounded font-bold text-emerald-800 dark:text-emerald-300 text-center">
                  ω = θ / t,   v = r · ω
                </div>
                <p className="font-sans text-slate-600 dark:text-slate-400 text-xs">
                  Angular speed <em>ω</em> (rad/sec) relates directly to tangential linear speed <em>v</em> (m/sec).
                </p>
              </div>
            </div>

            {/* Practice Exercise */}
            <div className="mt-8 space-y-6">
              <div className="p-6 bg-indigo-50 dark:bg-indigo-900/20 border-l-4 border-indigo-600">
                <h4 className="text-lg font-bold text-slate-900 dark:text-white mb-4">✏️ Practice Question 1: Circular Motion Kinematics</h4>
                <ExerciseQuestion 
                  question="A wheel of radius r = 0.5 meters rotates at 120 revolutions per minute (rpm). What is its angular speed ω in rad/sec and linear speed v in m/sec?"
                  options={[
                    'ω = 4π rad/sec ≈ 12.57 rad/s, v = 2π m/sec ≈ 6.28 m/s',
                    'ω = 2π rad/sec ≈ 6.28 rad/s, v = 1π m/sec ≈ 3.14 m/s',
                    'ω = 120 rad/sec, v = 60 m/sec',
                    'ω = 240π rad/sec, v = 120π m/sec'
                  ]}
                  correctAnswer={0}
                  explanation="Each revolution is 2π radians. 120 rpm = 120 × (2π rad) / 60 seconds = 4π rad/sec. Tangential linear speed v = r · ω = 0.5 m × (4π rad/s) = 2π m/sec ≈ 6.28 m/s."
                />
              </div>
            </div>
          </div>
        </section>

        {/* SUBTOPIC 4.2: Trigonometric Functions & Unit Circle */}
        <section id="subtopic-4.2" className="scroll-mt-8">
          <h2 className="text-base md:text-3xl font-bold text-slate-900 dark:text-white mb-3 md:mb-6 border-l-4 border-indigo-600 pl-2 md:pl-4 flex items-center gap-2">
            <span>⭕</span> 4.2. Unit Circle, Reference Angles & ASTC Rule
          </h2>

          <div className="space-y-4 md:space-y-6">
            <p className="text-xs md:text-lg text-slate-700 dark:text-slate-300 leading-relaxed">
              On the <strong>Unit Circle</strong> <em>x² + y² = 1</em>, any angle θ intersects at point <em>P(x, y) = (cos θ, sin θ)</em>:
            </p>

            <div className="p-4 bg-indigo-50 dark:bg-indigo-900/20 rounded-xl font-mono text-center text-xs md:text-sm font-bold text-indigo-900 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800/50 shadow-inner">
              {"sin(θ) = y,  cos(θ) = x,  tan(θ) = y / x,  csc(θ) = 1/y,  sec(θ) = 1/x,  cot(θ) = x/y"}
            </div>

            {/* Reference Angle Rules Card */}
            <div className="p-6 border border-slate-200 dark:border-slate-800 rounded-2xl bg-white dark:bg-slate-900 space-y-3">
              <h3 className="font-bold text-slate-900 dark:text-white text-sm md:text-base flex items-center gap-2">
                <span>🎯</span> Reference Angle (θ') Determination Rules
              </h3>
              <p className="text-xs md:text-sm text-slate-600 dark:text-slate-300">
                The reference angle <strong>θ'</strong> is the acute positive angle formed between the terminal side of θ and the <strong>x-axis</strong>:
              </p>
              <div className="grid md:grid-cols-4 gap-3 text-xs font-mono">
                <div className="p-3 bg-emerald-50 dark:bg-emerald-950/40 rounded-xl text-center border border-emerald-200">
                  <span className="font-bold text-emerald-900 dark:text-emerald-300 font-sans block mb-1">Quadrant I</span>
                  <div className="font-bold text-emerald-700 dark:text-emerald-200">θ' = θ</div>
                </div>
                <div className="p-3 bg-indigo-50 dark:bg-indigo-950/40 rounded-xl text-center border border-indigo-200">
                  <span className="font-bold text-indigo-900 dark:text-indigo-300 font-sans block mb-1">Quadrant II</span>
                  <div className="font-bold text-indigo-700 dark:text-indigo-200">θ' = 180° - θ</div>
                  <p className="text-[10px] font-sans text-slate-500 mt-1">θ' = π - θ</p>
                </div>
                <div className="p-3 bg-amber-50 dark:bg-amber-950/40 rounded-xl text-center border border-amber-200">
                  <span className="font-bold text-amber-900 dark:text-amber-300 font-sans block mb-1">Quadrant III</span>
                  <div className="font-bold text-amber-700 dark:text-amber-200">θ' = θ - 180°</div>
                  <p className="text-[10px] font-sans text-slate-500 mt-1">θ' = θ - π</p>
                </div>
                <div className="p-3 bg-purple-50 dark:bg-purple-950/40 rounded-xl text-center border border-purple-200">
                  <span className="font-bold text-purple-900 dark:text-purple-300 font-sans block mb-1">Quadrant IV</span>
                  <div className="font-bold text-purple-700 dark:text-purple-200">θ' = 360° - θ</div>
                  <p className="text-[10px] font-sans text-slate-500 mt-1">θ' = 2π - θ</p>
                </div>
              </div>
            </div>

            {/* Complete Special Angles Values Table */}
            <div className="p-6 border border-slate-200 dark:border-slate-800 rounded-2xl bg-white dark:bg-slate-900 shadow-sm space-y-4">
              <h3 className="text-base md:text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <span>⭐</span> Complete Special Angles Exact Value Matrix
              </h3>

              <div className="overflow-x-auto">
                <table className="w-full text-xs md:text-sm text-left border-collapse">
                  <thead>
                    <tr className="border-b border-slate-300 dark:border-slate-700 bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-white">
                      <th className="p-2.5">Degrees</th>
                      <th className="p-2.5">Radians</th>
                      <th className="p-2.5">sin(θ)</th>
                      <th className="p-2.5">cos(θ)</th>
                      <th className="p-2.5">tan(θ)</th>
                      <th className="p-2.5">csc(θ)</th>
                      <th className="p-2.5">sec(θ)</th>
                      <th className="p-2.5">cot(θ)</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200 dark:divide-slate-800 font-mono text-slate-700 dark:text-slate-300">
                    <tr>
                      <td className="p-2.5 font-bold font-sans">0°</td>
                      <td className="p-2.5">0</td>
                      <td className="p-2.5">0</td>
                      <td className="p-2.5 font-bold text-indigo-600">1</td>
                      <td className="p-2.5">0</td>
                      <td className="p-2.5 text-rose-500">Undef</td>
                      <td className="p-2.5">1</td>
                      <td className="p-2.5 text-rose-500">Undef</td>
                    </tr>
                    <tr>
                      <td className="p-2.5 font-bold font-sans">30°</td>
                      <td className="p-2.5">π / 6</td>
                      <td className="p-2.5">1 / 2</td>
                      <td className="p-2.5">√3 / 2</td>
                      <td className="p-2.5">√3 / 3</td>
                      <td className="p-2.5 font-bold text-indigo-600">2</td>
                      <td className="p-2.5">2√3 / 3</td>
                      <td className="p-2.5">√3</td>
                    </tr>
                    <tr>
                      <td className="p-2.5 font-bold font-sans">45°</td>
                      <td className="p-2.5">π / 4</td>
                      <td className="p-2.5">√2 / 2</td>
                      <td className="p-2.5">√2 / 2</td>
                      <td className="p-2.5 font-bold text-indigo-600">1</td>
                      <td className="p-2.5">√2</td>
                      <td className="p-2.5">√2</td>
                      <td className="p-2.5 font-bold text-indigo-600">1</td>
                    </tr>
                    <tr>
                      <td className="p-2.5 font-bold font-sans">60°</td>
                      <td className="p-2.5">π / 3</td>
                      <td className="p-2.5">√3 / 2</td>
                      <td className="p-2.5">1 / 2</td>
                      <td className="p-2.5 font-bold text-indigo-600">√3</td>
                      <td className="p-2.5">2√3 / 3</td>
                      <td className="p-2.5 font-bold text-indigo-600">2</td>
                      <td className="p-2.5">√3 / 3</td>
                    </tr>
                    <tr>
                      <td className="p-2.5 font-bold font-sans">90°</td>
                      <td className="p-2.5">π / 2</td>
                      <td className="p-2.5 font-bold text-indigo-600">1</td>
                      <td className="p-2.5">0</td>
                      <td className="p-2.5 text-rose-500">Undef</td>
                      <td className="p-2.5">1</td>
                      <td className="p-2.5 text-rose-500">Undef</td>
                      <td className="p-2.5">0</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {/* Practice Exercise */}
            <div className="mt-8 space-y-6">
              <div className="p-6 bg-indigo-50 dark:bg-indigo-900/20 border-l-4 border-indigo-600">
                <h4 className="text-lg font-bold text-slate-900 dark:text-white mb-4">✏️ Practice Question 2: Evaluating Non-Acute Angle</h4>
                <ExerciseQuestion 
                  question="Evaluate the exact value of tan(240°)."
                  options={[
                    'tan(240°) = √3',
                    'tan(240°) = -√3',
                    'tan(240°) = 1/√3',
                    'tan(240°) = -1'
                  ]}
                  correctAnswer={0}
                  explanation="240° lies in Quadrant III. Reference angle θ' = 240° - 180° = 60°. In Quadrant III, tangent is positive (+). Therefore, tan(240°) = +tan(60°) = √3."
                />
              </div>
            </div>
          </div>
        </section>

        {/* SUBTOPIC 4.3: Graphs of Trigonometric Functions */}
        <section id="subtopic-4.3" className="scroll-mt-8">
          <h2 className="text-base md:text-3xl font-bold text-slate-900 dark:text-white mb-3 md:mb-6 border-l-4 border-indigo-600 pl-2 md:pl-4 flex items-center gap-2">
            <span>🌊</span> 4.3. Sinusoidal Waves & 5-Key-Point Graphing Strategy
          </h2>

          <div className="space-y-4 md:space-y-6">
            <p className="text-xs md:text-lg text-slate-700 dark:text-slate-300 leading-relaxed">
              To sketch any transformed sinusoidal wave <em>y = A sin(B(x - C)) + D</em> or <em>y = A cos(B(x - C)) + D</em>, follow the <strong>5-Key-Point Algorithm</strong>:
            </p>

            {/* 5-Key-Point Strategy Step Cards */}
            <div className="p-6 bg-slate-50 dark:bg-slate-800/60 rounded-2xl border border-slate-200 dark:border-slate-700 space-y-3">
              <h4 className="font-bold text-slate-900 dark:text-white text-sm md:text-base flex items-center gap-2">
                <span>🛠️</span> 5-Step Sinusoidal Sketching Algorithm
              </h4>
              <ol className="list-decimal pl-5 text-xs md:text-sm text-slate-700 dark:text-slate-300 space-y-2">
                <li><strong>Identify Midline & Vertical Shift D:</strong> The central horizontal line of oscillation is <em>y = D</em>.</li>
                <li><strong>Determine Amplitude |A|:</strong> Maximum height = <em>D + |A|</em>, Minimum height = <em>D - |A|</em>.</li>
                <li><strong>Calculate Period T:</strong> Period <em>T = 2π / |B|</em>. Divide cycle into 4 equal sub-intervals: <em>Δx = T / 4</em>.</li>
                <li><strong>Determine Phase Shift C (Start Point):</strong> First key point begins at <em>x₀ = C</em>. Consecutive x-coordinates are <em>x₀, x₀ + Δx, x₀ + 2Δx, x₀ + 3Δx, x₀ + 4Δx</em>.</li>
                <li><strong>Plot Key Y-Values & Connect Smoothly:</strong> For Sine: [Mid, High, Mid, Low, Mid]. For Cosine: [High, Mid, Low, Mid, High].</li>
              </ol>
            </div>

            {/* Practice Exercise */}
            <div className="mt-8 space-y-6">
              <div className="p-6 bg-indigo-50 dark:bg-indigo-900/20 border-l-4 border-indigo-600">
                <h4 className="text-lg font-bold text-slate-900 dark:text-white mb-4">✏️ Practice Question 3: Sinusoidal Range & Period</h4>
                <ExerciseQuestion 
                  question="What is the range and period of the function f(x) = -3 sin(2x - π) + 1?"
                  options={[
                    'Range: [-2, 4], Period T = π',
                    'Range: [-3, 3], Period T = 2π',
                    'Range: [-4, 2], Period T = π',
                    'Range: [-2, 4], Period T = 2π'
                  ]}
                  correctAnswer={0}
                  explanation="Amplitude |A| = |-3| = 3. Midline D = 1. Range = [D - |A|, D + |A|] = [1 - 3, 1 + 3] = [-2, 4]. B = 2 ⟹ Period T = 2π / 2 = π."
                />
              </div>
            </div>
          </div>
        </section>

        {/* SUBTOPIC 4.4: Inverse Trigonometric Functions */}
        <section id="subtopic-4.4" className="scroll-mt-8">
          <h2 className="text-base md:text-3xl font-bold text-slate-900 dark:text-white mb-3 md:mb-6 border-l-4 border-indigo-600 pl-2 md:pl-4 flex items-center gap-2">
            <span>↩️</span> 4.4. Inverse Functions & Right-Triangle Evaluation
          </h2>

          <div className="space-y-4 md:space-y-6">
            <p className="text-xs md:text-lg text-slate-700 dark:text-slate-300 leading-relaxed">
              When evaluating composite expressions like <em>tan(arccos(x))</em> or <em>sin(arctan(u))</em>, construct an algebraic right triangle:
            </p>

            {/* Right Triangle Method Box */}
            <div className="p-6 border border-slate-200 dark:border-slate-800 rounded-2xl bg-white dark:bg-slate-900 space-y-3">
              <h3 className="font-bold text-slate-900 dark:text-white text-sm md:text-base flex items-center gap-2">
                <span>📐</span> Right-Triangle Geometric Construction Strategy
              </h3>
              <p className="text-xs md:text-sm text-slate-600 dark:text-slate-300">
                To simplify <strong>sin(arccos(x))</strong>:
              </p>
              <ol className="list-decimal pl-5 text-xs md:text-sm text-slate-700 dark:text-slate-300 space-y-1 font-mono">
                <li>Let θ = arccos(x) ⟹ cos(θ) = x / 1 = Adjacent / Hypotenuse.</li>
                <li>Draw a right triangle with Adjacent = x, Hypotenuse = 1.</li>
                <li>By Pythagorean Theorem, Opposite side = √(1 - x²).</li>
                <li>Read desired outer ratio: sin(θ) = Opposite / Hypotenuse = √(1 - x²).</li>
              </ol>
            </div>

            {/* Practice Exercise */}
            <div className="mt-8 space-y-6">
              <div className="p-6 bg-indigo-50 dark:bg-indigo-900/20 border-l-4 border-indigo-600">
                <h4 className="text-lg font-bold text-slate-900 dark:text-white mb-4">✏️ Practice Question 4: Composite Inverse Evaluation</h4>
                <ExerciseQuestion 
                  question="Evaluate tan(arcsin(3/5)) without a calculator."
                  options={[
                    'tan(θ) = 3/4',
                    'tan(θ) = 4/3',
                    'tan(θ) = 3/5',
                    'tan(θ) = 4/5'
                  ]}
                  correctAnswer={0}
                  explanation="Let θ = arcsin(3/5) ⟹ sin(θ) = 3/5 = Opposite / Hypotenuse. Opposite = 3, Hypotenuse = 5. By Pythagorean Theorem, Adjacent = √(5² - 3²) = √(25 - 9) = √16 = 4. Therefore, tan(θ) = Opposite / Adjacent = 3/4."
                />
              </div>
            </div>
          </div>
        </section>

        {/* SUBTOPIC 4.5: Identities */}
        <section id="subtopic-4.5" className="scroll-mt-8">
          <h2 className="text-base md:text-3xl font-bold text-slate-900 dark:text-white mb-3 md:mb-6 border-l-4 border-indigo-600 pl-2 md:pl-4 flex items-center gap-2">
            <span>✨</span> 4.5. Analytical Identities & Solving Trig Equations
          </h2>

          <div className="space-y-4 md:space-y-6">
            {/* Expanded Identities Summary Grid */}
            <div className="grid md:grid-cols-2 gap-4 text-xs md:text-sm font-mono">
              <div className="p-5 bg-white dark:bg-slate-900 rounded-2xl border border-indigo-200 dark:border-indigo-800 shadow-sm space-y-2">
                <h4 className="font-bold text-indigo-900 dark:text-indigo-300 font-sans text-sm">➕ Sum & Difference Formulas</h4>
                <div className="p-3 bg-indigo-50 dark:bg-indigo-900/30 rounded-xl space-y-1 text-center font-bold text-indigo-800 dark:text-indigo-200 text-xs">
                  <p>sin(α ± β) = sin α cos β ± cos α sin β</p>
                  <p>cos(α ± β) = cos α cos β ∓ sin α sin β</p>
                  <p>tan(α ± β) = (tan α ± tan β) / (1 ∓ tan α tan β)</p>
                </div>
              </div>

              <div className="p-5 bg-white dark:bg-slate-900 rounded-2xl border border-cyan-200 dark:border-cyan-800 shadow-sm space-y-2">
                <h4 className="font-bold text-cyan-900 dark:text-cyan-300 font-sans text-sm">⚡ Double & Half-Angle Formulas</h4>
                <div className="p-3 bg-cyan-50 dark:bg-cyan-900/30 rounded-xl space-y-1 text-center font-bold text-cyan-800 dark:text-cyan-200 text-xs">
                  <p>sin(2θ) = 2 sin θ cos θ</p>
                  <p>cos(2θ) = cos²θ - sin²θ = 2cos²θ - 1</p>
                  <p>sin(θ/2) = ± √[ (1 - cos θ) / 2 ]</p>
                </div>
              </div>
            </div>

            {/* Practice Exercise */}
            <div className="mt-8 space-y-6">
              <div className="p-6 bg-indigo-50 dark:bg-indigo-900/20 border-l-4 border-indigo-600">
                <h4 className="text-lg font-bold text-slate-900 dark:text-white mb-4">✏️ Practice Question 5: Multiple Angle Equation</h4>
                <ExerciseQuestion 
                  question="Find all solutions to sin(2x) = √3/2 in the interval [0, 2π)."
                  options={[
                    'x = π/6, 2π/6 (π/3), 7π/6, 8π/6 (4π/3)',
                    'x = π/3, 2π/3',
                    'x = π/6, 5π/6',
                    'x = π/12, 5π/12'
                  ]}
                  correctAnswer={0}
                  explanation="Let θ = 2x. sin(θ) = √3/2 ⟹ θ = π/3 + 2kπ or θ = 2π/3 + 2kπ. Dividing by 2: x = π/6 + kπ or x = π/3 + kπ. For k=0: x = π/6, π/3. For k=1: x = 7π/6, 4π/3. All 4 solutions lie in [0, 2π)."
                />
              </div>
            </div>
          </div>
        </section>

        {/* Navigation Buttons */}
        <div className="flex justify-between items-center pt-8 border-t border-slate-200 dark:border-slate-800">
          <button
            onClick={() => {
              if (onNavigateChapter) {
                onNavigateChapter('chapter3');
                window.scrollTo({ top: 0, behavior: 'smooth' });
              }
            }}
            className="flex items-center gap-2 px-4 md:px-6 py-2 md:py-3 bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 rounded-lg transition-colors font-medium text-sm md:text-base"
          >
            <svg className="w-4 h-4 md:w-5 md:h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Previous: Chapter 3
          </button>

          <button
            onClick={() => {
              if (onNavigateChapter) {
                onNavigateChapter('chapter5');
                window.scrollTo({ top: 0, behavior: 'smooth' });
              }
            }}
            className="flex items-center gap-2 px-4 md:px-6 py-2 md:py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg transition-colors font-medium text-sm md:text-base"
          >
            Next: Chapter 5
            <svg className="w-4 h-4 md:w-5 md:h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
          </button>
        </div>

      </div>
    </div>
  );
};

export default Chapter4;
