services:
  - type: web
    name: successbridge-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:702512%40Tol_Database@db.oxnntnvtkngfoorkleay.supabase.co:5432/postgres
      - key: JWT_SECRET
        value: SuccessBridge-Super-Secret-JWT-Key-For-Production-2024-Deployment-32-Characters
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://oxnntnvtkngfoorkleay.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94bm50bnZ0a25nZm9vcmtsZWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NzU5NzQsImV4cCI6MjA1MjI1MTk3NH0.sb_publishable_7cmmPTJwl0Nj7-nQWpWrvA_YgvBKTum
      - key: SUPABASE_SERVICE_KEY
        value: sb_secret_BnVbahCrOQufviYpHZewjw_6p9ykmQl
      - key: FRONTEND_URL
        value: https://successbridge.vercel.app
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: SUPER_ADMIN_EMAIL
        value: tolesatesfaye273@gmail.com
      - key: SUPER_ADMIN_PASSWORD
        value: 702512@Tol
      - key: SUPER_ADMIN_NAME
        value: Tolesa Tesfaye
      - key: ADMIN_EMAIL
        value: tolesatesfaye327@gmail.com
      - key: ADMIN_PASSWORD
        value: 702512@Tol
      - key: ADMIN_NAME
        value: Admin User